module.exports = {
	volumeLevels: [
		{ id: '0', label: '-30dB' },
		{ id: '1', label: '-29dB' },
		{ id: '2', label: '-28dB' },
		{ id: '3', label: '-27dB' },
		{ id: '4', label: '-26dB' },
		{ id: '5', label: '-25dB' },
		{ id: '6', label: '-24dB' },
		{ id: '7', label: '-23dB' },
		{ id: '8', label: '-22dB' },
		{ id: '9', label: '-21dB' },
		{ id: '10', label: '-20dB' },
		{ id: '11', label: '-19dB' },
		{ id: '12', label: '-18dB' },
		{ id: '13', label: '-17dB' },
		{ id: '14', label: '-16dB' },
		{ id: '15', label: '-15dB' },
		{ id: '16', label: '-14dB' },
		{ id: '17', label: '-13dB' },
		{ id: '18', label: '-12dB' },
		{ id: '19', label: '-11dB' },
		{ id: '20', label: '-10dB' },
		{ id: '21', label: '-9dB' },
		{ id: '22', label: '-8dB' },
		{ id: '23', label: '-7dB' },
		{ id: '24', label: '-6dB' },
		{ id: '25', label: '-5dB' },
		{ id: '26', label: '-4dB' },
		{ id: '27', label: '-3dB' },
		{ id: '28', label: '-2dB' },
		{ id: '29', label: '-1dB' },
		{ id: '30', label: '0dB' },
		{ id: '31', label: '1dB' },
		{ id: '32', label: '2dB' },
		{ id: '33', label: '3dB' },
		{ id: '34', label: '4dB' },
		{ id: '35', label: '5dB' },
		{ id: '36', label: '6dB' },
		{ id: '37', label: '7dB' },
		{ id: '38', label: '8dB' },
		{ id: '39', label: '9dB' },
		{ id: '40', label: '10dB' },
	],

	hpfChoices: [
		{ id: '0', label: 'Off' },
		{ id: '1', label: '80Hz' },
		{ id: '2', label: '120Hz' },
		{ id: '2', label: '160Hz' },
	],

	micGainChoices: [
		//1 to 11, -9db to +21db in 3db steps
		{ id: '1', label: '-9dB' },
		{ id: '2', label: '-6dB' },
		{ id: '3', label: '-3dB' },
		{ id: '4', label: '0dB' },
		{ id: '5', label: '3dB' },
		{ id: '6', label: '6dB' },
		{ id: '7', label: '9dB' },
		{ id: '8', label: '12dB' },
		{ id: '9', label: '15dB' },
		{ id: '10', label: '18dB' },
		{ id: '11', label: '21dB' },
	],

	polarityChoices: [
		{ id: '0', label: 'Omni' },
		{ id: '1', label: 'Cardioid' },
	],

	forcedMuteChoices: [
		{ id: '0', label: 'Off' },
		{ id: '1', label: 'Forced Unmute' },
		{ id: '2', label: 'Forced Mute' },
	],

	levelRFChoices: [
		{ id: '0', label: 'NO LINK' },
		{ id: '1', label: '-90dBm to -84dBm' },
		{ id: '2', label: '-84dBm to -78dBm' },
		{ id: '3', label: '-78dBm to -72dBm' },
		{ id: '4', label: '-72dBm to -66dBm' },
		{ id: '5', label: '-66dBm to -60dBm' },
		{ id: '6', label: '-60dBm to -54dBm' },
		{ id: '7', label: '-54dBm or more' },
	],

	levelAFRXChoices: [
		{ id: '0', label: 'NO LINK' },
		{ id: '1', label: '50dBFS to -40dBFS' },
		{ id: '2', label: '-40dBFS to -30dBFS' },
		{ id: '3', label: '-30dBFS to -20dBFS' },
		{ id: '4', label: '-20dBFS to -12dBFS' },
		{ id: '5', label: '-12dBFS to -6dBFS' },
		{ id: '6', label: '-6dBFS to -1dBFS' },
		{ id: '7', label: '-1dBFS or more' },
	],
}
