module.exports = {
	MODELS: [
		{
			id: 'esw-rs4180dan',
			label: 'ESW R4180DAN',
			actions: [
				'schmute',
				'schvolume',
				'schhpf',
				'rpresetcall',
				'stxmicgain',
				'stxintmicgain',
				'stxmicpolar',
				'stxforcedmute',
				'salltxforcedmute',
			],
			feedbacks: [
				'gchmute',
				'gchvolume',
				'gchhpf',
				'glastpreset',
				'gtxmicgain',
				'gtxintmicgain',
				'gtxmicpolar',
				'gtxforcedmute',
				'gstsmute',
			],
			variables: [
				'gchname',
				'gchmute',
				'gchvolume',
				'gchhpf',
				'glastpreset',
				'gtxmicgain',
				'gtxintmicgain',
				'gtxmicpolar',
				'gtxforcedmute',
				'glevelrf',
				'glevelafrx',
				'glevelbatttx',
				'glevelbatt',
				'gstsmute',
				'gtxname',
				'gtxlocationname',
			],
			data_request: [
				'gmyname',
				'gmydeviceid',
				'glocationname',
				'gpresetname',
				'grmgpresetname',
				'glastpreset',

				'gchname',
				'gchmute',
				'gchvolume',
				'gchhpf',
				'gtxmicgain',
				'gtxintmicgain',
				'gtxmicpolar',
				'gtxforcedmute',
				'glevelrf',
				'glevelafrx',
				'glevelbatttx',
				'glevelbatt',
				'gstsmute',
				'gtxname',
				'gtxlocationname',
			],
			channels: [
				{ id: '1', label: 'Channel 1', variableId: 'channel1' },
				{ id: '2', label: 'Channel 2', variableId: 'channel2' },
				{ id: '3', label: 'Channel 3', variableId: 'channel3' },
				{ id: '4', label: 'Channel 4', variableId: 'channel4' },
				{ id: '5', label: 'Channel 5', variableId: 'channel5' },
				{ id: '6', label: 'Channel 6', variableId: 'channel6' },
				{ id: '7', label: 'Channel 7', variableId: 'channel7' },
				{ id: '8', label: 'Channel 8', variableId: 'channel8' },
			],
		},
		{
			id: 'esw-r4180lk',
			label: 'ESW R4180LK',
			actions: [
				'schmute',
				'schvolume',
				'schhpf',
				'rpresetcall',
				'stxmicgain',
				'stxintmicgain',
				'stxmicpolar',
				'stxforcedmute',
				'salltxforcedmute',
			],
			feedbacks: [
				'gchmute',
				'gchvolume',
				'gchhpf',
				'glastpreset',
				'gtxmicgain',
				'gtxintmicgain',
				'gtxmicpolar',
				'gtxforcedmute',
				'gstsmute',
			],
			variables: [
				'gchname',
				'gchmute',
				'gchvolume',
				'gchhpf',
				'glastpreset',
				'gtxmicgain',
				'gtxintmicgain',
				'gtxmicpolar',
				'gtxforcedmute',
				'glevelrf',
				'glevelafrx',
				'glevelbatttx',
				'glevelbatt',
				'gstsmute',
				'gtxname',
				'gtxlocationname',
			],
			data_request: [
				'gmyname',
				'gmydeviceid',
				'glocationname',
				'gpresetname',
				'grmgpresetname',
				'glastpreset',

				'gchname',
				'gchmute',
				'gchvolume',
				'gchhpf',
				'gtxmicgain',
				'gtxintmicgain',
				'gtxmicpolar',
				'gtxforcedmute',
				'glevelrf',
				'glevelafrx',
				'glevelbatttx',
				'glevelbatt',
				'gstsmute',
				'gtxname',
				'gtxlocationname',
			],
			channels: [
				{ id: '1', label: 'Channel 1', variableId: 'channel1' },
				{ id: '2', label: 'Channel 2', variableId: 'channel2' },
				{ id: '3', label: 'Channel 3', variableId: 'channel3' },
				{ id: '4', label: 'Channel 4', variableId: 'channel4' },
				{ id: '5', label: 'Channel 5', variableId: 'channel5' },
				{ id: '6', label: 'Channel 6', variableId: 'channel6' },
				{ id: '7', label: 'Channel 7', variableId: 'channel7' },
				{ id: '8', label: 'Channel 8', variableId: 'channel8' },
			],
		},
		{
			id: 'esw-chg',
			label: 'ESW CHG4/5',
			actions: [
				'schmute',
				'schvolume',
				'schhpf',
				'rpresetcall',
				'stxmicgain',
				'stxintmicgain',
				'stxmicpolar',
				'stxforcedmute',
				'salltxforcedmute',
			],
			feedbacks: [
				'gchmute',
				'gchvolume',
				'gchhpf',
				'glastpreset',
				'gtxmicgain',
				'gtxintmicgain',
				'gtxmicpolar',
				'gtxforcedmute',
				'gstsmute',
			],
			variables: [
				'gchname',
				'gchmute',
				'gchvolume',
				'gchhpf',
				'glastpreset',
				'gtxmicgain',
				'gtxintmicgain',
				'gtxmicpolar',
				'gtxforcedmute',
				'glevelrf',
				'glevelafrx',
				'glevelbatttx',
				'glevelbatt',
				'gstsmute',
				'gtxname',
				'gtxlocationname',
			],
			data_request: [
				'gmyname',
				'gmydeviceid',
				'glocationname',
				'gpresetname',
				'grmgpresetname',
				'glastpreset',

				'gchname',
				'gchmute',
				'gchvolume',
				'gchhpf',
				'gtxmicgain',
				'gtxintmicgain',
				'gtxmicpolar',
				'gtxforcedmute',
				'glevelrf',
				'glevelafrx',
				'glevelbatttx',
				'glevelbatt',
				'gstsmute',
				'gtxname',
				'gtxlocationname',
			],
			channels: [
				{ id: '1', label: 'Channel 1', variableId: 'channel1' },
				{ id: '2', label: 'Channel 2', variableId: 'channel2' },
				{ id: '3', label: 'Channel 3', variableId: 'channel3' },
				{ id: '4', label: 'Channel 4', variableId: 'channel4' },
				{ id: '5', label: 'Channel 5', variableId: 'channel5' },
			],
		},
	],
}
